<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_home' => 'Home',
    'page' => 'Page',
    'gallerij' => 'gallerij',
  ),
  'article' => 
  array (
    'articles/ajaxform' => 'Ajax Form',
  ),
);


/* Auto generated by Themes Administration on : 2015.10.07 12:03:04 */
